---
plugin: aws_ec2
#aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
#aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>
regions:
  - us-east-1
filters:
  tag:Name:
    - WebServer in ASG
  instance-state-name : running

#keyed_groups:
 # - key: tags
  #  prefix: tag